apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: homeassistant
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/prod
    repoURL: https://github.com/daniva6/homeassistant.git
    targetRevision: v1.0.4
  syncPolicy:
    syncOptions:
    - CreateNamespace=true       

