apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: urbackup
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: cephfs-hdd-r2-squid
  volumeMode: Filesystem

