apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-backups-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: cephfs-hdd-r2
  volumeMode: Filesystem

