apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  labels:
    app.kubernetes.io/name: homeassistant
spec:
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
        app.kubernetes.io/name: homeassistant
    spec:
      containers:
      - image: homeassistant/home-assistant:2025.4
        imagePullPolicy: IfNotPresent
        name: homeassistant
        ports:
        - containerPort: 8123
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: homeassistant-pvc
        - mountPath: /config/backups
          name: homeassistant-backups-pvc
      volumes:
      - name: homeassistant-pvc
        persistentVolumeClaim:
          claimName: homeassistant-squid
      - name: homeassistant-backups-pvc
        persistentVolumeClaim:
          claimName: homeassistant-backups-squid
