apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
spec:
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
      - image: homeassistant/home-assistant:2024.11
        imagePullPolicy: IfNotPresent
        name: homeassistant
        ports:
        - containerPort: 8123
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: homeassistant-pvc
        - mountPath: /srv
          name: homeassistant-backups-pvc
      volumes:
      - name: homeassistant-pvc
        persistentVolumeClaim:
          claimName: homeassistant-pvc
      - name: homeassistant-backups-pvc
        persistentVolumeClaim:
          claimName: homeassistant-backups-pvc
