apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homeassistant-tls
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`homeassistant.dev.vogelfamily.ch`)
    services:
    - name: homeassistant
      port: 8123
---      
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homeassistant
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`homeassistant.dev.vogelfamily.ch`)
    middlewares:
    - name: redirect-https
      namespace: traefik
    services:
    - name: homeassistant
      port: 8123
