apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-squid
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: cephrbd-r2-squid


