apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homeassistant-tls
  annotations:
    avp.kubernetes.io/path: "k8s-secrets/data/homesassistant"  
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`<dsn>`)
    services:
    - name: homeassistant
      port: 8123
---      
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homeassistant
  annotations:
    avp.kubernetes.io/path: "k8s-secrets/data/homesassistant"  
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`<dsn>`)
    middlewares:
    - name: redirect-https
      namespace: traefik
    services:
    - name: homeassistant
      port: 8123
