apiVersion: v1
kind: Service
metadata:
  name: homeassistant
spec:
  ports:
  - name: homeassistant
    port: 8123
    protocol: TCP
    targetPort: 8123
  selector:
    app: homeassistant
  type: ClusterIP

